// Property Data
export const Property = [
  {
    id: 1,
    property_name: "Ajmera I Land",
    property_country: "India",
    property_city: "Mumbai",
    property_address: "Ajmera I Land, Bhakti Park, Wadala East, Mumbai",
    property_description: "Ajmera I Land",
    owner_of_property: "Ajmera I Land",
    property_type: "Apartment",
    no_of_bedrooms: 2,
    no_of_bathrooms: 2,
    property_area: 1100,
    propery_price: 1200,
    property_image:
      "https://is1-2.housingcdn.com/01c16c28/0d51dbec350d860481b6e97a4685a236/v0/fs/2_bhk_apartment-for-rent-wadala_east-Mumbai-hall.jpg",
    date: "2022-11-06",
  },
  {
    id: 2,
    property_name: "Omkar Ananta",
    property_country: "India",
    property_city: "Mumbai",
    property_address: "Omkar Ananta, Municipal Colony, Goregaon East, Mumbai",
    property_description:
      "This Apartment can be a comfortable and affordable home for your family. It is a 2 BHK unit available on rent at Goregaon East in Mumbai. This Apartment comes with a plethora of amenities to meet your modern lifestyle needs. It is Furnished. It is located on floor 1 of the building having a total 21 floors. Offering beautiful city views, this 2 BHK has been thoughtfully developed. It includes a total of 2 bedrooms and 2 bathroom. The property is North-East facing. It also includes 0 balcony that can be a perfect place for relaxation. The built-up area of the Apartment is 1031 Square feet. The carpet area is 900 Square feet. The Apartment is available for a monthly rent of Rs 50000. The security deposit payable is Rs 200000.",
    owner_of_property: "Omkar Ananta",
    property_type: "Apartment",
    no_of_bedrooms: 2,
    no_of_bathrooms: 2,
    property_area: 900,
    propery_price: 620,
    property_image:
      "https://is1-3.housingcdn.com/01c16c28/5431511fed1660ad8b6ff479f300b1d0/v0/fs/2_bhk_apartment-for-rent-goregaon_east-Mumbai-hall.jpg",
    date: "2022-12-07",
  },
  {
    id: 3,
    property_name: "Mynd Property",
    property_country: "USA",
    property_city: "Texas",
    property_address: "11923 Medicine Bow Cir, Houston, TX 77067",
    property_description:
      "11923 Medicine Bow Cir is a cozy and inviting home with 1360 square feet of living area, three bedrooms, two bathrooms, and an attached two car garage. It boasts a nicely remodeled interior with an amazing floor plan. Cooking is a breeze in the lovely kitchen that comes with essential appliances for your convenience. Additionally, a dedicated laundry area is available complete with hookups. Located only 30 minutes from downtown Houston, in proximity to I-45 and a wide array of amenities.",
    owner_of_property: "Mynd Property",
    property_type: "House",
    no_of_bedrooms: 3,
    no_of_bathrooms: 2,
    property_area: 1360,
    propery_price: 1875,
    property_image:
      "https://photos.zillowstatic.com/fp/79e4813c44640b2a9018fadda79766db-uncropped_scaled_within_1536_1152.webp",
    date: "2022-11-10",
  },
  {
    id: 4,
    property_name: "Red Wagon Properties",
    property_country: "USA",
    property_city: "Texas",
    property_address: "1735 Alice Hl, San Antonio, TX 78232",
    property_description:
      "~Beautiful home on an oversized treed lot~Saltillo tile in the living/dining/kitchen, & parquet wood flooring in the bedrooms~Master bedroom has 3 closets, bath has a double vanity~2nd bedroom has 2 closets, built-in drawers~Kitchen has a double oven & an abundance of cabinets & storage~Spacious living room has cathedral ceilings, a gas fireplace~Air-conditioned Florida room w/built in cabinets overlooks the beautiful backyard~Great location near the airport/281/Bitters~NEISD schools~Mandatory ",
    owner_of_property: "Red Wagon Properties",
    property_type: "House",
    no_of_bedrooms: 2,
    no_of_bathrooms: 2,
    property_area: 1953,
    propery_price: 1995,
    property_image:
      "https://photos.zillowstatic.com/fp/9d7c61f9592ff389e18f9d9a7ef44555-uncropped_scaled_within_1536_1152.webp",
    date: "2022-11-08",
  },
  {
    id: 5,
    property_name: "Wavecrest Gardens",
    property_country: "USA",
    property_city: "New York, NY",
    property_address: "20-10 Seagirt Blvd, Far Rockaway, NY 11691",
    property_description:
      "Wavecrest Gardens is a beautifully landscaped, gated community, adjacent to Rockaway Beach. Featuring blossoming greenery and waterfront breezes, the community offers everyday conveniences including on-site laundry facilities, a fitness center, and on-site parking. Find yourself near multiple transit options, and a quick 45-minute commute to Manhattan on the A train. Sunlit apartments feature renovated kitchens, spacious layouts, and a range of floorplan options. Come see why life is better at the beach in Far Rockaway.",
    owner_of_property: "Wavecrest Gardens",
    property_type: "Apartment",
    no_of_bedrooms: 2,
    no_of_bathrooms: 1,
    property_area: 1100,
    propery_price: 1875,
    property_image:
      "https://photos.zillowstatic.com/fp/5c03e39a6223b64a934f8441dc056241-cc_ft_768.webp",
    date: "2022-11-07",
  },
  {
    id: 6,
    property_name: "Avalon Brooklyn Bay",
    property_country: "USA",
    property_city: "New York, NY",
    property_address: "1524 Sheepshead Bay Rd, Brooklyn, NY 11235",
    property_description:
      "Avalon Brooklyn Bay features furnished and unfurnished studio, 1, 2, and 3 bedroom Sheepshead Bay apartment homes.  Avalon Brooklyn Bay features furnished and unfurnished studio, 1, 2, and 3 bedroom Sheepshead Bay apartment homes.",
    owner_of_property: "Avalon Brooklyn Bay",
    property_type: "Apartment",
    no_of_bedrooms: 1,
    no_of_bathrooms: 1,
    property_area: 3578,
    propery_price: 6785,
    property_image:
      "https://photos.zillowstatic.com/fp/1a3387202523c450e5372272a76e62bc-cc_ft_768.webp",
    date: "2022-12-05",
  },
  {
    id: 7,
    property_name: "Highland Village",
    property_country: "USA",
    property_city: "Kansas, MO",
    property_address: "8619 E 61st Ter, Kansas City, MO 64129",
    property_description:
      "Wavecrest Gardens is a beautifully landscaped, gated community, adjacent to Rockaway Beach. Featuring blossoming greenery and waterfront breezes, the community offers everyday conveniences including on-site laundry facilities, a fitness center, and on-site parking. Find yourself near multiple transit options, and a quick 45-minute commute to Manhattan on the A train. Sunlit apartments feature renovated kitchens, spacious layouts, and a range of floorplan options. Come see why life is better at the beach in Far Rockaway.",
    owner_of_property: "Highland Village",
    property_type: "House",
    no_of_bedrooms: 1,
    no_of_bathrooms: 1,
    property_area: 620,
    propery_price: 781,
    property_image:
      "https://photos.zillowstatic.com/fp/15f2817a5f8418fc1c05375eff0dca10-cc_ft_768.webp",
    date: "2022-11-07",
  },
  {
    id: 8,
    property_name: "New Longview",
    property_country: "USA",
    property_city: "Boston, MA",
    property_address: "1350 Boylston St, Boston, MA 02215",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "Harlo",
    property_type: "Apartment",
    no_of_bedrooms: 2,
    no_of_bathrooms: 1,
    property_area: 442,
    propery_price: 3356,
    property_image:
      "https://photos.zillowstatic.com/fp/5c8b4e84ea21d37e113e2752a697772b-uncropped_scaled_within_1536_1152.webp",
    date: "2022-11-15",
  },
  {
    id: 9,
    property_name: "Modern Real Estate",
    property_country: "USA",
    property_city: "Boston, MA",
    property_address: "122 Lake St, Brighton, MA 02135",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "Harlo",
    property_type: "House",
    no_of_bedrooms: 8,
    no_of_bathrooms: 4,
    property_area: 3000,
    propery_price: 8500,
    property_image:
      "https://photos.zillowstatic.com/fp/2e8e920bad6f7500fab27f8d5a9011d1-cc_ft_768.webp",
    date: "2022-11-11",
  },
  {
    id: 10,
    property_name: "Aranson Maguire Group",
    property_country: "USA",
    property_city: "Boston, MA",
    property_address: "234 Bowen St, South Boston, MA 02127",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "Aranson Maguire Group",
    property_type: "House",
    no_of_bedrooms: 3,
    no_of_bathrooms: 1.5,
    property_area: 1014,
    propery_price: 4000,
    property_image:
      "https://photos.zillowstatic.com/fp/404f92c5d0256ecbb0be5d51a308f8f6-cc_ft_768.webp",
    date: "2022-11-10",
  },
  {
    id: 11,
    property_name: "Park Place Townhome",
    property_country: "USA",
    property_city: "New York, NY",
    property_address: "100 Athol St, Buffalo, NY 1422",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "Park Place Townhome",
    property_type: "House",
    no_of_bedrooms: 2,
    no_of_bathrooms: 1,
    property_area: 600,
    propery_price: 784,
    property_image:
      "https://photos.zillowstatic.com/fp/440b421f93184c51af7952ddac7894c8-cc_ft_384.webp",
    date: "2022-11-10",
  },
  {
    id: 12,
    property_name: "Cedarwood Apartments",
    property_country: "USA",
    property_city: "New York, NY",
    property_address: "10 Cedarwood Blvd, Baldwinsville, NY 13027",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "Aranson Maguire Group",
    property_type: "Apartment",
    no_of_bedrooms: 1,
    no_of_bathrooms: 1,
    property_area: 680,
    propery_price: 764,
    property_image:
      "https://photos.zillowstatic.com/fp/876b5519ee9f4087d7f5d1907776f2da-cc_ft_768.webp",
    date: "2022-11-20",
  },
  {
    id: 13,
    property_name: "One Eleven",
    property_country: "USA",
    property_city: "New York, NY",
    property_address: "111 East Ave, Rochester, NY 14604",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "One Eleven",
    property_type: "Apartment",
    no_of_bedrooms: 1,
    no_of_bathrooms: 1,
    property_area: 600,
    propery_price: 804,
    property_image:
      "https://photos.zillowstatic.com/fp/421d950a410e45cbcf9e7ce695eeff77-cc_ft_768.webp",
    date: "2022-11-20",
  },
  {
    id: 14,
    property_name: "Rosewood",
    property_country: "USA",
    property_city: "New York, NY",
    property_address: "172 Rosewood Ter #174, Rochester, NY 14609 ",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "Rosewood",
    property_type: "Townhomes",
    no_of_bedrooms: 3,
    no_of_bathrooms: 1,
    property_area: 1048,
    propery_price: 1250,
    property_image:
      "https://maps.googleapis.com/maps/api/streetview?location=172+Rosewood+Ter%2C+Rochester%2C+NY+14609&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=fz7FdywYMYsNq48BOlH4mSNC62g=",
    date: "2022-11-15",
  },
  {
    id: 15,
    property_name: "New Key Performance",
    property_country: "USA",
    property_city: "New York, NY",
    property_address: "349 Thurston Rd, Rochester, NY 14619",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "New Wickham",
    property_type: "Townhomes",
    no_of_bedrooms: 1,
    no_of_bathrooms: 1,
    property_area: 1540,
    propery_price: 850,
    property_image:
      "https://photos.zillowstatic.com/fp/d72b2a9f284677035b6a5642da2a6854-cc_ft_768.webp",
    date: "2022-11-15",
  },
  {
    id: 16,
    property_name: "Thomas Berry",
    property_country: "USA",
    property_city: "Winnipeg, WP",
    property_address: "249 Thomas Berry St, Winnipeg, MB R2H 0R2",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "New Wickham",
    property_type: "Townhomes",
    no_of_bedrooms: 1,
    no_of_bathrooms: 1,
    property_area: 1207,
    propery_price: 1750,
    property_image:
      "https://photos.zillowstatic.com/fp/e1b13dbe939a4884f99928606e674780-cc_ft_768.webp",
    date: "2022-11-17",
  },
  {
    id: 17,
    property_name: "Aerodrome",
    property_country: "USA",
    property_city: "Regina, SK",
    property_address: "5635 Aerodrome Rd #48-B, Regina, SK S4W 0M3 ",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "Aerodrome",
    property_type: "Townhomes",
    no_of_bedrooms: 2,
    no_of_bathrooms: 2,
    property_area: 1207,
    propery_price: 1500,
    property_image:
      "https://maps.googleapis.com/maps/api/streetview?location=5635+Aerodrome+Rd+%2348-B%2C+Regina%2C+SK+S4W0M3&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=4d9_ztOIPv54CEKftxOcttwkDyk=",
    date: "2022-11-17",
  },
  {
    id: 18,
    property_name: "Cornwall St",
    property_country: "USA",
    property_city: "Regina, SK",
    property_address: "375 Cornwall St, Regina, SK S4R 2G7",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "Cornwall St",
    property_type: "House",
    no_of_bedrooms: 3,
    no_of_bathrooms: 1,
    property_area: 756,
    propery_price: 1500,
    property_image:
      "https://photos.zillowstatic.com/fp/5b8db01085db8aa3794bde03d541046c-cc_ft_768.webp",
    date: "2022-11-17",
  },
  {
    id: 19,
    property_name: "Aerodrome",
    property_country: "USA",
    property_city: "Regina, SK",
    property_address: "703 Quince St, Omak, WA 98841",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "Aerodrome",
    property_type: "House",
    no_of_bedrooms: 2,
    no_of_bathrooms: 2,
    property_area: 1401,
    propery_price: 702,
    property_image:
      "https://photos.zillowstatic.com/fp/82bbff982fa6bfa8493d00f2eb8cad11-cc_ft_768.webp",
    date: "2022-11-17",
  },
  {
    id: 20,
    property_name: "Faxon Commons",
    property_country: "USA",
    property_city: "Regina, SK",
    property_address: "1037 Southern Artery, Quincy, MA 02169",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "Aerodrome",
    property_type: "House",
    no_of_bedrooms: 1,
    no_of_bathrooms: 1,
    property_area: 638,
    propery_price: 2003,
    property_image:
      "https://photos.zillowstatic.com/fp/eac1e9fca9a32f7d14b9525e1f51e1e6-cc_ft_768.webp",
    date: "2022-11-17",
  },
  {
    id: 21,
    property_name: "Lincoln Heights",
    property_country: "USA",
    property_city: "Quincy, MA",
    property_address: "175 Centre St, Quincy, MA 02169",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "Quincy, MA",
    property_type: "House",
    no_of_bedrooms: 1,
    no_of_bathrooms: 1,
    property_area: 618,
    propery_price: 2130,
    property_image:
      "https://photos.zillowstatic.com/fp/f381432ad4d7352fb57bb1583836c427-cc_ft_768.webp",
    date: "2022-11-17",
  },
  {
    id: 22,
    property_name: "Alister Quincy",
    property_country: "USA",
    property_city: "Quincy, MA",
    property_address: "500 Falls Blvd, Quincy, MA 02169",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "Alister Quincy",
    property_type: "House",
    no_of_bedrooms: 1,
    no_of_bathrooms: 1,
    property_area: 698,
    propery_price: 2230,
    property_image:
      "https://photos.zillowstatic.com/fp/9355e097ca41cf88604eced3cc973be7-cc_ft_768.webp",
    date: "2022-11-17",
  },
  {
    id: 23,
    property_name: "Nova Quincy",
    property_country: "USA",
    property_city: "Quincy, MA",
    property_address: "1500 Hancock St, Quincy, MA 02169",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "Quincy, MA",
    property_type: "House",
    no_of_bedrooms: 1,
    no_of_bathrooms: 1,
    property_area: 580,
    propery_price: 2200,
    property_image:
      "https://photos.zillowstatic.com/fp/c3bd5672156dfefa61ea8e212e3a6bb8-cc_ft_384.webp",
    date: "2022-11-17",
  },
  {
    id: 24,
    property_name: "Quarry Hills    ",
    property_country: "USA",
    property_city: "Quincy, MA",
    property_address: "333 Ricciuti Dr, Quincy, MA 02169    ",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "Quincy, MA",
    property_type: "Apartment",
    no_of_bedrooms: 1,
    no_of_bathrooms: 1,
    property_area: 740,
    propery_price: 2395,
    property_image:
      "https://photos.zillowstatic.com/fp/4e8bb04e2f197d9e895f438f1acfe44c-cc_ft_768.webp",
    date: "2022-11-17",
  },
  {
    id: 25,
    property_name: "Lincoln Heights",
    property_country: "USA",
    property_city: "Quincy, MA",
    property_address: "34 Arnold St, Quincy, MA 02169",
    property_description:
      "The Harlo is home to 212 brand new boutique-style apartment homes located in the vibrant Fenway neighborhood. The Harlo is a short walk to the stadium, T station, Longwood Medical Area (LMA), graduate schools, and myriad arts and cultural institutions. With unsurpassed indoor-outdoor amenities, and interiors are designed by MarkZeff, the options for sophisticated living choices are endless, flexible, comfortable, and an extension of home.",
    owner_of_property: "Quincy, MA",
    property_type: "Townhomes",
    no_of_bedrooms: 3,
    no_of_bathrooms: 1,
    property_area: 1218,
    propery_price: 2395,
    property_image:
      "https://photos.zillowstatic.com/fp/0c361bfa831fce942f16eb3bfab9b0b7-cc_ft_768.webp",
    date: "2022-11-17",
  },
];
